### ISSUE TITLE
"Go to http://192.168.33.10"

### ISSUE THREAD

**Issue by dmzone** [ryanaltvater/generator-liquid#2]
Infinite pending.
http://192.168.33.10/

**Comment by ryanaltvater** [comment]
Hey @dmzone, sorry I'm just now seeing this. Can you explain? Is the virtual machine running?

**Comment by dmzone** [comment]
hi @ryanaltvater, now everything works... it was my bad.

**Comment by ryanaltvater** [comment]
@dmzone No problem, glad to hear. 👍
